improved script - a lot

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,5 +1,5 @@
 #!/bin/sh
-set -ex
+set -e
 
 # enables go 1.5 vendor experiment
 export GO15VENDOREXPERIMENT=1
@@ -83,47 +83,92 @@ upload() {
   done
 }
 
-OPTIND=1
-while getopts ":u:r:b:m:e:" opt; do
-  case "$opt" in
-    u)
-      OWNER="$OPTARG"
+usage() {
+  cat <<EOF
+NAME:
+  $0 - Builds and releases a go binary to github releases
+USAGE:
+  $0 [options]
+OPTIONS:
+  -h, --help                Shows this screen
+  -u, --user, --owner       Repository owner (e.g.: caarlos0)
+  -r, --repo                Repository name (e.g.: go-releaser)
+  -b, --binary              Binary final name (e.g.: antibody)
+  -m, --main                Path to the main golang file (e.g.: cmd/main.go)
+  -e, --extra               Extra files to package: (e.g.: USAGE.md)
+EOF
+}
+
+test $# -eq 0 && {
+  usage
+  exit 0
+}
+
+while test $# -gt 0; do
+  case "$1" in
+    -u|--user|--owner)
+      shift
+      if [ $# -gt 0 ]; then
+        export OWNER="$1"
+        shift
+      fi
       ;;
-    r)
-      REPO="$OPTARG"
+    -r|--repo)
+      shift
+      if [ $# -gt 0 ]; then
+        export REPO="$1"
+        shift
+      fi
       ;;
-    b)
-      BINARY="$OPTARG"
+    -b|--binary)
+      shift
+      if [ $# -gt 0 ]; then
+        export BINARY="$1"
+        shift
+      fi
       ;;
-    m)
-      MAINGO="$OPTARG"
+    -m|--main)
+      shift
+      if [ $# -gt 0 ]; then
+        export MAINGO="$1"
+        shift
+      fi
       ;;
-    e)
-      EXTRA_FILES="$OPTARG"
+    -e|--extra)
+      shift
+      if [ $# -gt 0 ]; then
+        export EXTRA_FILES="$1"
+        shift
+      fi
       ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
+    --help|-h)
+      usage
+      exit 0
+      ;;
+    *)
+      echo "Invalid option $1. Run $0 -h for help" >&2
       exit 1
       ;;
   esac
 done
 
 test -z "$OWNER" && {
-  echo "Missing owner (-u ownername)" >&2
+  echo "Missing owner" >&2
   exit 1
 }
 test -z "$REPO" && {
-  echo "Missing repository (-r reponame)" >&2
+  echo "Missing repository" >&2
   exit 1
 }
 test -z "$BINARY" && {
-  echo "Missing binary (-b binaryname)" >&2
+  echo "Missing binary name" >&2
   exit 1
 }
 test -z "$MAINGO" && {
-  echo "Missing main.go file (-m path/to/main.go/folder)" >&2
+  echo "Missing main go file" >&2
   exit 1
 }
+
 cleanup
 CURRENT="$(git describe --tags --abbrev=0)"
 PREVIOUS=$(git describe --tags --abbrev=0 "$CURRENT"^)
